# Doble Joomla with Let's Encrypt in a Docker Compose

# Deploy Joomla server with a Docker Compose using the command:
# docker compose -f joomla-traefik-letsencrypt-docker-compose.yml -p joomla up -d

volumes:
  mysql-data:
  joomla-data:
  joomla2-data:
  traefik-certificates:

services:
  mysql:
    # Image tag (replace with yours)
    image: mysql:8
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      # Database name (replace with yours)
      MYSQL_DATABASE: joomladb
      # Database user (replace with yours)
      MYSQL_USER: joomladbuser
      # Database password (replace with yours)
      MYSQL_PASSWORD: zi4viuWY9kqkAABab6BQ
      # MySQL root password (replace with yours)
      MYSQL_ROOT_PASSWORD: Ldcb3wPGBPqAg2ank3VG
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  joomla:
    # Image tag (replace with yours)
    image: joomla:4.1
    volumes:
      - joomla-data:/var/www/html
    environment:
      JOOMLA_DB_HOST: mysql
      # Database name (replace with yours)
      JOOMLA_DB_NAME: joomladb
      # Database user (replace with yours)
      JOOMLA_DB_USER: joomladbuser
      # Database password (replace with yours)
      JOOMLA_DB_PASSWORD: zi4viuWY9kqkAABab6BQ
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      - "traefik.enable=true"
      # Joomla URL (replace with yours)
      - "traefik.http.routers.joomla.rule=Host(`joomla.domain.ex`)"
      - "traefik.http.routers.joomla.service=joomla"
      - "traefik.http.routers.joomla.entrypoints=websecure"
      - "traefik.http.services.joomla.loadbalancer.server.port=80"
      - "traefik.http.routers.joomla.tls=true"
      - "traefik.http.routers.joomla.tls.certresolver=letsencrypt"
      - "traefik.http.services.joomla.loadbalancer.passhostheader=true"
      - "traefik.http.routers.joomla.middlewares=compresstraefik"
      - "traefik.http.middlewares.compresstraefik.compress=true"
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      traefik:
        condition: service_healthy

  joomla2:
    # Image tag (replace with yours)
    image: joomla:3.10
    volumes:
      - joomla2-data:/var/www/html
    environment:
      JOOMLA_DB_HOST: mysql
      # Database name (replace with yours)
      JOOMLA_DB_NAME: joomladb
      # Database user (replace with yours)
      JOOMLA_DB_USER: joomladbuser
      # Database password (replace with yours)
      JOOMLA_DB_PASSWORD: zi4viuWY9kqkAABab6BQ
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      - "traefik.enable=true"
      # Joomla URL (replace with yours)
      - "traefik.http.routers.joomla2.rule=Host(`joomla2.domain.ex`)"
      - "traefik.http.routers.joomla2.service=joomla2"
      - "traefik.http.routers.joomla2.entrypoints=websecure"
      - "traefik.http.services.joomla2.loadbalancer.server.port=80"
      - "traefik.http.routers.joomla2.tls=true"
      - "traefik.http.routers.joomla2.tls.certresolver=letsencrypt"
      - "traefik.http.services.joomla2.loadbalancer.passhostheader=true"
      - "traefik.http.routers.joomla2.middlewares=compresstraefik"
      - "traefik.http.middlewares.compresstraefik.compress=true"
    restart: unless-stopped
    depends_on: 
      mysql:
        condition: service_healthy
      traefik:
        condition: service_healthy

  traefik:
    # Image tag (replace with yours)
    image: traefik:2.8
    command:
      - "--log.level=WARN"
      - "--accesslog=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--ping=true"
      - "--ping.entrypoint=ping"
      - "--entryPoints.ping.address=:8082"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # Email for Let's Encrypt (replace with yours)
      - "--certificatesresolvers.letsencrypt.acme.email=mail@mail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certificates:/etc/traefik/acme
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8082/ping","--spider"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      - "traefik.enable=true"
      # Traefik URL (replace with yours)
      - "traefik.http.routers.dashboard.rule=Host(`traefik.domain.ex`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.dashboard.loadbalancer.passhostheader=true"
      - "traefik.http.routers.dashboard.middlewares=authtraefik"
      # Basic Authentication for Traefik Dashboard
      # Username: traefikadmin (replace with yours)
      # Passwords must be encoded using MD5, SHA1, or BCrypt https://hostingcanada.org/htpasswd-generator/
      - "traefik.http.middlewares.authtraefik.basicauth.users=traefikadmin:{SHA}1OHW5sjX3U633U7Bwdfnj6o7n4Y="
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    restart: unless-stopped
